//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Metro_El_Engaz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stations
    {
        public int St_ID { get; set; }
        public string St_Name { get; set; }
    
        public virtual End_Station End_Station { get; set; }
        public virtual Start_Station Start_Station { get; set; }
    }
}
