//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Metro_El_Engaz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tickets
    {
        public int ID { get; set; }
        public string Price { get; set; }
        public string Num_of_Stations { get; set; }
        public string Destination { get; set; }
        public int SSN { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
